version: "3"

services:

  bash:
    image: quay.io/natlibfi/annif
    volumes:
      - ${ANNIF_PROJECTS}:/annif-projects
    user: ${MY_UID}:${MY_GID}
    stdin_open: true
    tty: true
    command: bash

  gunicorn_server:
    image: quay.io/natlibfi/annif
    volumes:
      - ${ANNIF_PROJECTS}:/annif-projects
    user: ${MY_UID}:${MY_GID}
    command: ["gunicorn", "annif:create_app()", "--bind", "0.0.0.0:5000", "--timeout", "600"]

  nginx:
    image: nginx
    volumes:
      - ./annif/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5000:80"
    depends_on:
      - gunicorn_server